# Generated by Django 4.2.3 on 2023-07-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customerID',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customerID',
            new_name='customer',
        ),
    ]
