# Generated by Django 4.2.3 on 2023-07-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_order', '0003_remove_order_cart_item_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='credit_card',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
