# Generated by Django 4.2.3 on 2023-07-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_order', '0004_bill_credit_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('done', 'Done')], default='new', max_length=50, null=True),
        ),
    ]
